services:
  nats:
    image: nats
    ports:
      - "4222:4222"
  publisher:
    build:
      context: .
      args:
        BINARY: publisher
    links:
      - nats
    environment:
      - NATS=nats
  subscriber:
    build:
      context: .
      args:
        BINARY: subscriber
    links:
      - nats
    environment:
      - NATS=nats
